services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizmaster
      POSTGRES_PASSWORD: quizmasterpass